### ISSUE TITLE
Dockerfile - Any reason not to use the python image?

### ISSUE THREAD

**Issue by tvories** [zaknye/xcel_itron2mqtt#13]
Is there a reason you're using `FROM alpine` in your dockerfile and then installing python.  Any reason not to use the official python container? https://hub.docker.com/_/python

**Comment by zaknye** [comment]
Mainly for size. Just compared the size of the container resulting from the current Docker file: `95.2MB`. The size of the proposed replacement is `128MB'. I guess it's not a big differences, and removes the one step that takes the longest amount of time. 

Really, biggest reason is size. Any other reason to switch?

**Comment by tvories** [comment]
There is also an alpine python container, though this discussion goes into why some folks are avoiding alpine: https://news.ycombinator.com/item?id=10782897

I guess it is mostly preference (and your preference).  I'd prefer to let the actual python developers maintain my base docker image for me, but your image works, so it's totally preference.  It also makes your docker file simpler, but not like it's a complex docker file as is
