### ISSUE TITLE
TimeoutError: Waiting too long to get response from meter

### ISSUE THREAD

**Issue by fishcharlie** [zaknye/xcel_itron2mqtt#16]
Even tho my smart meter is connected to my WiFi network and has an IP address it seems like it isn't discoverable via mDNS. I would try to set the `METER_IP` manually, but in the documentation it states:

> Port number of the meter, must be set if METER_IP is set.

And I have no idea how to get the port number.

Any ideas on how to move forward here?

**Comment by zaknye** [comment]
Hey Charlie, sorry about that. I have updated the README to include the default port as supplied by the Xcel documentation.

Try using `5353`

**Comment by fishcharlie** [comment]
@zaknye Hmm. Getting connection timeout errors now. Might need to contact Xcel to see what is up.

**Comment by zaknye** [comment]
@fishcharlie Just touching base, did this solve your issue?

**Comment by fishcharlie** [comment]
@zaknye Nope. I ended up just doing a command line in Home Assistant.

The weird thing is I was trying to do this on macOS. And even the `curl` commands didn't work on macOS due to the cipher.

But it worked fine on Home Assistant itself.

Don't necessarily love this solution. But it works.

```
  - platform: command_line
    unique_id: xcel_energy_meter_power
    name: "Xcel Energy Meter Power"
    command: "OPENSSL_CONF=/config/xcelenergy_meter/openssl.conf /usr/bin/curl --ciphers ECDHE-ECDSA-AES128-CCM8 --insecure --url https://10.0.0.1:8081/upt/1/mr/1/r --cert /config/xcelenergy_meter/certs/.cert.pem --key /config/xcelenergy_meter/certs/.key.pem 2>&1 | grep -o '<value>.*</value>' | grep -Eo '[0-9]+'"
    unit_of_measurement: "W"
    value_template: "{{ float(value) if is_number(value_json) }}"
    device_class: 'power'
    scan_interval: 20 # was 91 previously
    command_timeout: 16

  - platform: command_line
    unique_id: xcel_energy_meter_consumption
    name: "Xcel Energy Meter Consumption"
    command: "OPENSSL_CONF=/config/xcelenergy_meter/openssl.conf /usr/bin/curl --ciphers ECDHE-ECDSA-AES128-CCM8 --insecure --url https://10.0.0.1:8081/upt/1/mr/3/r --cert /config/xcelenergy_meter/certs/.cert.pem --key /config/xcelenergy_meter/certs/.key.pem 2>&1 | grep -o '<value>.*</value>' | grep -Eo '[0-9]+'"
    unit_of_measurement: "kWh"
    value_template: "{{ float(value) | multiply(0.001) | round(3) if is_number(value) }}"
    device_class: 'energy'
    state_class: 'total_increasing'
    scan_interval: 20 # was 91 previously
    command_timeout: 16
```

**Comment by zaknye** [comment]
Were you trying to run the container under Docker Desktop for MacOS? I had similar problems working with MacOS and moved over to running solely on Linux.
