### ISSUE TITLE
Default Port is not 5353 on my meter

### ISSUE THREAD

**Issue by c2bull** [zaknye/xcel_itron2mqtt#18]
Hi, very much appreciate this effort! Got it successfully setup yesterday, noticed in the README doc that the default port for the meter is 5353 and I'm not sure if mine is something special but an nmap probe shows mine is actually only alive on 8081. As soon as I set that port in my environment everything started working. 

Nmap scan:

$ sudo nmap -A -T4 192.168.1.123
Starting Nmap 7.93 ( https://nmap.org ) at 2023-07-19 11:31 MDT
Nmap scan report for 192.168.1.123
Host is up (0.018s latency).
Not shown: 999 filtered tcp ports (no-response)
PORT     STATE SERVICE              VERSION
8081/tcp open  ssl/blackice-icecap?
MAC Address: B4:23:30:22:88:EB (Itron)
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
Device type: general purpose
Running: Linux 3.X|4.X
OS CPE: cpe:/o:linux:linux_kernel:3 cpe:/o:linux:linux_kernel:4
OS details: Linux 3.10 - 4.11, Linux 3.2 - 4.9
Network Distance: 1 hop

Can the doc be updated to indicate using either of those ports (in case the 5353 doesn't work)?

**Comment by zaknye** [comment]
Yup, I think you're right. I believe I may have seen 8081 while testing and developing originally, but the docs claimed that `5353` was default so I just pushed that change without checking 👀

Also, the port should be resolved automatically when starting the container, let me know if that is also for some reason not working for you.

**Comment by c2bull** [comment]
I was having issues with the container resolving the IP so I added that into my env, which meant I needed to specify the port as well which is why I noticed.

My home network is... special... and the local mDNS names only sometimes work.

**Comment by zaknye** [comment]
OK, I figured as much. 

Just committed the change and will merge so it doesn't send others on wild goose chases.
