### ISSUE TITLE
Trying to add to HACS but getting error message about repository

### ISSUE THREAD

**Issue by crmfyi** [zaknye/xcel_itron2mqtt#21]
When I add a custom repository for this to HACS, I get the following error message and can't proceed. 

<Integration zaknye/xcel_itron2mqtt> Repository structure for main is not compliant

**Comment by zaknye** [comment]
This repo was never meant to be integrated into the HACS environment. It is meant to be run as a microservice separate from your Homeassistant installation as a docker container.

To run this you need an MQTT broker setup then to run this as a container pointed towards that broker.

**Comment by crmfyi** [comment]
OK. Thank you for the clarification.
