### ISSUE TITLE
Add support for providing the IP address for the meter

### ISSUE THREAD

**Issue by tvories** [zaknye/xcel_itron2mqtt#8]
I have my smart meter in another VLAN from where this mqtt container lives.  mDNS is flaky when traversing networks.  I would like to provide an IP address to the container via environment variable to skip the mDNS step.

**Comment by zaknye** [comment]
Beat me to it! I figured some users would have similar hangups with mDNS. I figured I'd start with the easiest solution and work backwards. 

Should have some fixes coming this week, I'll lump this in there as an option and if designated skip the mDNS query entirely.

**Comment by tvories** [comment]
Nice.  I was going to submit a PR eventually but if you've already got a plan that's great.

**Comment by tvories** [comment]
@zaknye I just found out that mDNS wasn't working because I was running my docker container from my Windows WSL setup.  WSL has issues with mDNS working without some tweaking.  I am able to see the device if I run it outside WSL, but I thought it was an interesting discovery 😄

**Comment by zaknye** [comment]
@tvories 
Yup, that'll do it. I've been a fan of WSL2, but ended up building a dedicated linux dev box for reasons similar to that, along with the lack of linux headers within the VM making it impossible to do any profiling work,
